# Generated by Django 4.2.5 on 2023-09-17 14:08

from django.db import migrations, models
from movies.models import Movie
import csv
import datetime


def load_initial_data(apps, schema_editor):
    movies_arr = []
    with open('movies/migrations/movies.csv', 'r', encoding='utf-8') as all_movies_file:
        all_movies_file.readline()
        reader = csv.reader(all_movies_file, delimiter=',')

        for row in reader:
            movie = Movie(tmdb_id=row[1], original_title=row[5], overview=row[11], popularity=float(row[2]),
                          release_date=datetime.datetime.strptime(row[15], '%m/%d/%Y'), vote_average=float(row[17]),
                          vote_count=int(row[16]), cast=row[6], genres=row[13], director=row[8], keywords=row[10])
            movies_arr.append(movie)

        Movie.objects.bulk_create(movies_arr)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=1000)),
                ('overview', models.TextField()),
                ('popularity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('release_date', models.DateField()),
                ('vote_average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vote_count', models.IntegerField()),
                ('cast', models.CharField(max_length=1000)),
                ('genres', models.CharField(max_length=1000)),
                ('director', models.CharField(max_length=1000)),
                ('keywords', models.TextField()),
            ],
        ),
        migrations.RunPython(load_initial_data),
    ]
