# Generated by Django 4.2.5 on 2023-09-17 14:08

import django
import csv
import datetime

from django.db import migrations, models

from movies.models import Movie, MovieStatistics


def load_initial_data(apps, schema_editor):
    with open('movies/migrations/movies.csv', 'r', encoding='utf-8') as all_movies_file:
        all_movies_file.readline()
        reader = csv.reader(all_movies_file, delimiter=',')

        for row in reader:
            statistics = MovieStatistics(vote_average=float(row[17]), vote_count=int(row[16]), popularity=float(row[2]))
            movie = Movie(tmdb_id=row[1], original_title=row[5], overview=row[11],
                          release_date=datetime.datetime.strptime(row[15], '%m/%d/%Y'),
                          cast=row[6], genres=row[13], director=row[8], keywords=row[10])
            statistics.save()
            movie.statistics = statistics
            movie.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
                ('update_date', models.DateField()),
                ('owner', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5),
                                                                       django.core.validators.MaxLengthValidator(
                                                                           100)])),
            ],
        ),
        migrations.CreateModel(
            name='MovieStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_average', models.DecimalField(decimal_places=2, max_digits=5,
                                                     validators=[django.core.validators.MinValueValidator(1)])),
                ('vote_count', models.IntegerField()),
                ('popularity', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=1000)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('cast', models.CharField(max_length=1000)),
                ('genres', models.CharField(max_length=1000)),
                ('director', models.CharField(max_length=1000)),
                ('keywords', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('statistics',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.moviestatistics')),
            ],
        ),
        migrations.RunPython(load_initial_data)
    ]
