# Generated by Django 4.2.5 on 2023-09-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_user_alter_moviecollection_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecollection',
            name='movies',
            field=models.ManyToManyField(to='movies.movie'),
        ),
    ]
